Repository MasterLaplace/Engine-3D, pull requests merged in 2023-10, with the labels that each got.

#14 docs(.github): put the correct name of the project
  .github/PULL_REQUEST_TEMPLATE.md
  .github/SUPPORT.md
  LICENSE
  VERSION
Labels: documentation, enhancement

#15 12 Implement Laplace Library
  Libs/LaplaceError/include/laplace_error.h
  Libs/LaplaceLib/lib_two_free.c
  Libs/LaplaceLib/lib_two_print.c
  Libs/LaplaceLink/include/laplace_link.h
  Libs/LaplaceLink/link_remove.c
  Libs/LaplaceMap/include/laplace_map.h
  Libs/Makefile
  Libs/README.md
  Libs/VERSION
Labels: documentation, enhancement, optimizing

#16 13 Implement Laplace Launcher
  Launcher/src/SceneManager.py
  Launcher/src/Widgets.py
  Launcher/src/__main__.py
Labels: documentation, duplicate

#18 17 Implement a Version Management
  Launcher/src/SceneManager.py
  Makefile
Labels: documentation, enhancement

#20 19 Implement Engine Module
  Engine/Config/GraphicsLibrary/graphics.h
  Engine/Config/OperatingSystem/distribution.h
  Engine/Config/Version/version.h
  Engine/Config/config.h
  Engine/Engine/Clock/clock.c
  Engine/Engine/Clock/engine_clock.h
  Engine/Engine/Event/engine_event.h
  Engine/Engine/Math/Geometry/math_geometry.h
  Engine/Engine/Math/Geometry/triangle.c
  Engine/Engine/Math/Matrix/math_matrix.h
  Engine/Engine/Math/Matrix/matrix.c
  Engine/Engine/Math/Point/math_point.h
  Engine/Engine/Math/Point/point.c
  Engine/Engine/Math/Vector/math_vector.h
  Engine/Engine/Math/Vector/vector3.c
  Engine/Engine/Math/Vector/vector4.c
  Engine/Engine/Math/engine_math.h
  Engine/Engine/Window/engine_window.h
  Engine/Engine/Window/window.c
  Engine/Engine/engine.c
  Engine/Engine/engine.h
  Engine/core.c
  Launcher/Makefile
  Makefile
Labels: documentation, enhancement, optimizing

#22 21 Fix Build Error
  .gitignore
  Launcher/Makefile
  Launcher/requirements.txt
  Makefile
  Scripts/install_csfml.sh
Labels: bug

#23 fix(libs): fix build error
  .github/workflows/doxygen-gh-pages.yml
  .gitmodules
  Doxyfile.cfg
  Libs/Makefile
Labels: bug, libs, patch
